name: Flutter CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: kindlink_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4          

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"    
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run Linter
        run: flutter analyze --no-fatal-infos --no-fatal-warnings || true

      - name: Run Unit Tests
        run: flutter test

      - name: Build project
        run: flutter build web